"""
Claudette smoke test 2: end-to-end through DSL.

Tests the claim:
    A role.md file produced by smoke test 1 (Claudette + wrapper)
    can be dropped into a DSL office, built via `dsl build`, and run
    via `dsl run`, producing sensible output on cached test articles.

Steps:
    1. Locate the credibility_scorer.md generated by smoke test 1.
       (If missing, instruct user to run smoke test 1 first.)
    2. Create a temp office directory:
         <tmp>/credibility_test/
           ├── office.md             (defines the test office)
           ├── articles.jsonl        (3 cached test articles)
           └── roles/
               └── credibility_scorer.md  (copied from smoke test 1)
    3. Run `dsl build <office_dir>`. Report success/failure.
    4. Run `dsl run <office_dir>`. Report success/failure.
    5. Read results.jsonl and verify:
       - one record per input article
       - each has `score` and `reasoning` fields
       - scores are valid floats in [0, 1]
       - reasonings are non-empty strings
    6. Report pass/fail with details.

Requires ANTHROPIC_API_KEY in the environment for the run step (the
agent calls Claude). Without the key, `dsl build` should still
succeed (validates the role file is well-formed); only `dsl run`
will fail. Both outcomes are useful information.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from textwrap import dedent


_THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_THIS_DIR.parent))


# ── Where smoke test 1 saves its output ───────────────────────────────

SMOKE_TEST_1_OUTPUTS = _THIS_DIR / "smoke_test_outputs"
CREDIBILITY_SCORER_FILE = SMOKE_TEST_1_OUTPUTS / "credibility_scorer.md"


# ── Cached test articles ──────────────────────────────────────────────

TEST_ARTICLES = [
    {
        "title": "Federal Reserve announces 25 basis point rate increase",
        "body": (
            "The Federal Reserve announced a 25 basis point increase to "
            "the federal funds rate on Wednesday, bringing the target "
            "range to 5.25-5.50 percent. The decision was unanimous "
            "among voting members of the Federal Open Market Committee. "
            "Fed Chair Jerome Powell said in a press conference that "
            "inflation remains above the committee's 2 percent target "
            "but has shown signs of moderating. Treasury yields rose "
            "modestly following the announcement, while equity markets "
            "closed the day marginally lower."
        ),
        "source": "Reuters",
    },
    {
        "title": "SHOCKING: Aliens built the pyramids, new study claims",
        "body": (
            "A bombshell new report from independent researcher Dr. Truth "
            "(who declined to provide his real name or credentials) "
            "REVEALS that the great pyramids of Giza were absolutely "
            "definitely built by extraterrestrial beings thousands of "
            "years ago. Mainstream archaeologists DON'T WANT YOU TO "
            "KNOW THIS but the evidence is overwhelming. Insider sources "
            "(who cannot be named for safety reasons) have confirmed "
            "the cover-up extends to the highest levels of government."
        ),
        "source": "AnonymousBlog.example",
    },
    {
        "title": "City council approves new bike lane on Main Street",
        "body": (
            "The Springfield City Council voted 5-2 on Tuesday evening "
            "to approve construction of a protected bike lane along the "
            "Main Street corridor between 1st Avenue and 12th Avenue. "
            "Construction is expected to begin in August and complete "
            "before the end of the year. The project, which was funded "
            "through a state transportation grant of $1.2 million, was "
            "supported by the city's transportation planning department "
            "and opposed by some downtown business owners who expressed "
            "concerns about parking. Council member Maria Chen, who "
            "introduced the proposal, said the lane is part of a "
            "longer-term effort to expand the city's bike network."
        ),
        "source": "Springfield Daily Gazette",
    },
]


# ── Office.md template ────────────────────────────────────────────────

OFFICE_MD = dedent("""\
    # Office: credibility_test

    Sources: file_source(filepath="articles.jsonl", format="jsonl")
    Sinks: jsonl_recorder(path="results.jsonl")

    Agents:
    Scorer is a credibility_scorer.
    Scorer's AI is claude_precise.

    Connections:
    file_source's destination is Scorer.
    Scorer's out is jsonl_recorder.
""")


# ── Validation ────────────────────────────────────────────────────────

def check_role_file_exists() -> bool:
    if CREDIBILITY_SCORER_FILE.is_file():
        return True
    print("FAIL: credibility_scorer.md not found.")
    print(f"  Looked for: {CREDIBILITY_SCORER_FILE}")
    print()
    print("  Run smoke test 1 first to generate the role file:")
    print(f"    python3 {_THIS_DIR}/smoke_test.py")
    return False


def setup_office(tmp_dir: Path) -> Path:
    """Create the test office directory structure. Returns office dir."""
    office_dir = tmp_dir / "credibility_test"
    office_dir.mkdir()
    (office_dir / "roles").mkdir()
    (office_dir / "office.md").write_text(OFFICE_MD)
    with (office_dir / "articles.jsonl").open("w") as f:
        for article in TEST_ARTICLES:
            f.write(json.dumps(article) + "\n")
    shutil.copy(CREDIBILITY_SCORER_FILE, office_dir / "roles" / "credibility_scorer.md")
    return office_dir


def run_dsl(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    """Run a dsl CLI command, capturing output."""
    return subprocess.run(
        ["dsl"] + args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=120,
    )


def validate_results(results_path: Path) -> tuple[bool, list[str]]:
    """Return (passed, list_of_check_messages)."""
    messages: list[str] = []
    if not results_path.is_file():
        messages.append(f"✗ results.jsonl not found at {results_path}")
        return False, messages

    lines = [
        line for line in results_path.read_text().splitlines()
        if line.strip()
    ]
    n = len(lines)
    expected = len(TEST_ARTICLES)
    if n != expected:
        messages.append(
            f"✗ expected {expected} result records, got {n}"
        )
    else:
        messages.append(f"✓ correct number of records ({n})")

    passed = (n == expected)
    for i, line in enumerate(lines):
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            messages.append(f"✗ record {i} is not valid JSON")
            passed = False
            continue

        # Score check
        if "score" not in obj:
            messages.append(f"✗ record {i} missing 'score' field")
            passed = False
        else:
            try:
                s = float(obj["score"])
                if 0.0 <= s <= 1.0:
                    messages.append(
                        f"✓ record {i}: score={s:.2f} ({TEST_ARTICLES[i]['source'][:20]})"
                    )
                else:
                    messages.append(
                        f"✗ record {i}: score={s} outside [0, 1]"
                    )
                    passed = False
            except (TypeError, ValueError):
                messages.append(
                    f"✗ record {i}: score={obj['score']!r} not a number"
                )
                passed = False

        # Reasoning check
        if "reasoning" not in obj:
            messages.append(f"✗ record {i} missing 'reasoning' field")
            passed = False
        elif not str(obj["reasoning"]).strip():
            messages.append(f"✗ record {i}: reasoning is empty")
            passed = False

    return passed, messages


# ── Driver ────────────────────────────────────────────────────────────

def main() -> int:
    print("=" * 70)
    print("CLAUDETTE SMOKE TEST 2 — generated agent runs through DSL")
    print("=" * 70)
    print()

    print("[1/5] Locating role file from smoke test 1...")
    if not check_role_file_exists():
        return 1
    print(f"  OK — found {CREDIBILITY_SCORER_FILE}")
    print()

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        print(f"[2/5] Setting up test office in {tmp_path}...")
        office_dir = setup_office(tmp_path)
        print(f"  OK — office at {office_dir}")
        for f in sorted(office_dir.rglob("*")):
            if f.is_file():
                rel = f.relative_to(office_dir)
                print(f"    {rel} ({f.stat().st_size} bytes)")
        print()

        print(f"[3/5] Running `dsl build {office_dir.name}`...")
        # Build is run with the office dir as a relative path from tmp_path
        # because that mirrors how `dsl build <office>` is normally invoked.
        build_result = run_dsl(["build", office_dir.name], cwd=tmp_path)
        if build_result.returncode != 0:
            print(f"  FAIL — `dsl build` exited with code {build_result.returncode}")
            print(f"  stdout:\n{build_result.stdout}")
            print(f"  stderr:\n{build_result.stderr}")
            return 1
        print("  OK — dsl build succeeded")
        # Show the build's stdout/stderr trimmed so we know what happened
        if build_result.stdout.strip():
            print(f"  stdout: {build_result.stdout.strip()[:200]}")
        print()

        if not os.environ.get("ANTHROPIC_API_KEY"):
            print("[4/5] Skipping `dsl run` — no ANTHROPIC_API_KEY set.")
            print("  Build succeeded; the role file is structurally valid")
            print("  and DSL can compile it into an office.")
            print()
            print("  To run the full smoke test, set ANTHROPIC_API_KEY and")
            print("  re-run this script.")
            return 0

        print(f"[4/5] Running `dsl run {office_dir.name}`...")
        run_result = run_dsl(["run", office_dir.name], cwd=tmp_path)
        if run_result.returncode != 0:
            print(f"  FAIL — `dsl run` exited with code {run_result.returncode}")
            print(f"  stdout:\n{run_result.stdout}")
            print(f"  stderr:\n{run_result.stderr}")
            return 1
        print("  OK — dsl run completed")
        if run_result.stdout.strip():
            print(f"  stdout (last 300 chars): ...{run_result.stdout.strip()[-300:]}")
        print()

        print("[5/5] Validating results.jsonl...")
        results_path = office_dir / "results.jsonl"
        passed, messages = validate_results(results_path)
        for m in messages:
            print(f"  {m}")

        # Persist the artifacts for inspection (tmpdir is about to vanish).
        persistent = _THIS_DIR / "smoke_test_2_outputs"
        persistent.mkdir(exist_ok=True)
        if results_path.exists():
            shutil.copy(results_path, persistent / "results.jsonl")
            print(f"  results saved to {persistent / 'results.jsonl'}")

        print()
        if passed:
            print("PASS — Claudette-generated agent runs correctly through DSL.")
            return 0
        else:
            print("FAIL — see validation messages above.")
            return 1


if __name__ == "__main__":
    sys.exit(main())
